### ISSUE TITLE
I can't get slash commands working

### ISSUE THREAD

**Issue by meliooff** [FnrDev/slash-commands#58]
My slash commands files are loading but I can't use any slash command and I don't know why ; my discord bot has administrator permissions with the slash commands scope..
Can you tell me how is the file **slash.js** (in the root) loaded ? Because I saw nowhere the loading of this file in your code

**Comment by FnrDev** [comment]
You need to run the `slash.js` file to register slash commands

`node slash.js`
And will load all commands and register them

**Comment by meliooff** [comment]
But when I start my bot I do `node index.js`
Should I do `node slash.js` once and then I can start my bot again and again or should I put a `require('./slash.js')` line in my index.js ?

**Comment by FnrDev** [comment]
No need to require a slash.js file

- slash.js file, it just registers new commands, so if you add new command just run the file once before starting your bot

**Comment by meliooff** [comment]
Alright it's working, thank you so much
