### ISSUE TITLE
I can't get the slash command

### ISSUE THREAD

**Issue by Hyenz** [FnrDev/slash-commands#75]
I've seen the previous issue that similar to my problem but none of them are working 

So first of all my bot are working fine. Whe  I run `node index.js` it's working fine but there's no slash command registered in the server although the bot have been given a right scope and administrator permission in the server. I tried to run `node slash.js` but it's comes out with error in the console.

**Comment by FnrDev** [comment]
Can you send a screenshot of the error?

**Comment by Hyenz** [comment]
I will send it once I'm on my pc shortly.

**Comment by FnrDev** [comment]
Any news?
